### ISSUE TITLE
Only left Zed camera is displaying image.

### ISSUE THREAD

**Issue by chan-e91** [stereolabs/zed-python#12]
Hi,
 I was able to capture images only from the left camera. 
I tried to change the "PyVIEW.PyVIEW_LEFT" to "PyVIEW.PyVIEW_RIGHT" in camera.pyx file but to no use ( as VIEW_RIGHT was defined ), can you please tell me how to take left and right images, and rectify them using this wrapper .

**Comment by adujardin** [comment]
Hi,
To get the right image in the example you can replace [this line](https://github.com/stereolabs/zed-python/blob/master/examples/live_camera.py#L58)
`cam.retrieve_image(mat)` by `cam.retrieve_image(mat, sl.PyVIEW.PyVIEW_RIGHT)`

You should not change directly the wrapper because you're only changing the default value.

**Comment by chan-e91** [comment]
thanks for the quick reply, the images we get from this are rectified ?

**Comment by adujardin** [comment]
Yes, to get the unrectified images call it with `VIEW_LEFT_UNRECTIFIED` (the complete list is [here](https://github.com/stereolabs/zed-python/blob/master/pyzed/defines.pxd#L112))

**Comment by chan-e91** [comment]
yes, I needed only rectified images. Thanks for the help.!!
