### ISSUE TITLE
Support for Jetson Xavier

### ISSUE THREAD

**Issue by S4WRXTTCS** [stereolabs/zed-python#57]
As far as I can tell the Jetson Xavier requires ZED SDK 2.7, but the zed-python only mentions support for ZED SDK 2.3

Has this been tested with the Jetson Xavier that has ZED SDK 2.7 installed?

I tried building/installing this, but I'm getting a permissions error during the install.

creating /usr/local/lib/python3.6/dist-packages/pyzed
error: could not create '/usr/local/lib/python3.6/dist-packages/pyzed': Permission denied

**Comment by adujardin** [comment]
Since the python wrapper has to be compiled, you can use it with any recent version of the ZED SDK (>=2.3) . 
Some features will be missing though but the platform support is the same as the ZED SDK.

For the permission issue, you should call the install script with `sudo`;
` sudo python3 setup.py install`
